[phases.setup]
nixPkgs = ["python311", "chromium", "nss", "nspr", "atk", "cups", "libdrm", "mesa", "libgbm", "pango", "cairo", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "xorg.libXkbcommon"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[start]
cmd = "python server.py"
